# Generate scripts/gitversion.h from git: the release name (nearest tag), the
# full version (tag + commits-since + short hash + -dirty marker) and a build
# timestamp.
#
# Run as a CMake script, not included:
#   cmake -DSRC_DIR=<repo> -DOUT=<header> -P gitversion.cmake

# Full version string: nearest tag, commits since it, short hash, and an
# automatic -dirty suffix for uncommitted tracked changes. Falls back to a bare
# short hash, then to "unknown" outside a git tree.
execute_process(
   COMMAND git -C "${SRC_DIR}" describe --tags --always --dirty=-dirty --abbrev=7
   OUTPUT_VARIABLE GIT_VERSION
   OUTPUT_STRIP_TRAILING_WHITESPACE
   RESULT_VARIABLE GIT_RESULT
   ERROR_QUIET
)
if(NOT GIT_RESULT EQUAL 0 OR GIT_VERSION STREQUAL "")
   set(GIT_VERSION "unknown")
endif()

# Release name: just the nearest tag, e.g. v1.28. This is the single source of
# truth for the release number - bump it by creating a git tag, not by editing
# source. "dev" when the tree has no reachable tag.
execute_process(
   COMMAND git -C "${SRC_DIR}" describe --tags --abbrev=0
   OUTPUT_VARIABLE GIT_RELEASE
   OUTPUT_STRIP_TRAILING_WHITESPACE
   RESULT_VARIABLE TAG_RESULT
   ERROR_QUIET
)
if(NOT TAG_RESULT EQUAL 0 OR GIT_RELEASE STREQUAL "")
   set(GIT_RELEASE "dev")
endif()

string(TIMESTAMP BUILD_DATE "%Y-%m-%d %H:%M:%S")

file(WRITE "${OUT}"
   "/* Auto-generated by scripts/gitversion.cmake - do not edit, do not commit. */\n"
   "#define RELEASENAME \"${GIT_RELEASE}\"\n"
   "#define GITVERSION  \"${GIT_VERSION}\"\n"
   "#define BUILD_DATE  \"${BUILD_DATE}\"\n"
)

message(STATUS "gitversion.h: ${GIT_RELEASE} / ${GIT_VERSION}  ${BUILD_DATE}")
